name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          if [ $(find . -name '*.test.js' | wc -l) -eq 0 ]; then
            echo "::error::No tests found"
            exit 1
          else
            npm test -- --ci --maxWorkers=2
          fi
